openapi: 3.1.0
info:
  title: 고용⦁산재보험 가입 사업장 정보 API
  description: 고용보험 또는 산재보험으로 가입된 사업장의 정보를 조회하는 공공데이터 API입니다.
  version: "1.0.0"
servers:
  - url: https://apis.data.go.kr/B490001/gySjbPstateInfoService
paths:
  /getGySjBoheomBsshItem:
    get:
      summary: 고용⦁산재보험 가입 사업장 조회
      operationId: getInsuranceData
      parameters:
        - name: serviceKey
          in: query
          required: true
          description: 공공데이터포털 인증키
          schema:
            type: string
        - name: opaBoheomFg
          in: query
          required: true
          description: 보험 구분 (1: 산재, 2: 고용)
          schema:
            type: string
        - name: v_saeopjaDrno
          in: query
          required: false
          description: 사업자등록번호 (선택)
          schema:
            type: string
        - name: pageNo
          in: query
          required: false
          description: 페이지 번호 (기본값: 1)
          schema:
            type: integer
            default: 1
        - name: numOfRows
          in: query
          required: false
          description: 한 페이지당 조회 건수 (기본값: 10)
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 사업장 정보 응답(XML 형식)
          content:
            application/xml:
              schema:
                type: string
components: {}