openapi: 3.1.0
info:
  title: 고용⦁산재보험 가입 사업장 API
  description: 사업자등록번호를 이용해 고용 또는 산재보험 가입 정보를 조회하는 API입니다.
  version: 1.0.0

servers:
  - url: https://emply-insu-api.onrender.com

paths:
  /insurance:
    get:
      summary: 고용⦁산재보험 가입 사업장 정보 조회
      operationId: getInsuranceData
      parameters:
        - in: query
          name: opaBoheomFg
          required: true
          description: 보험 구분 (1: 산재, 2: 고용)
          schema:
            type: string
            enum: ["1", "2"]
        - in: query
          name: v_saeopjaDrno
          required: false
          description: 사업자등록번호 (예: 2208623066)
          schema:
            type: string
      responses:
        "200":
          description: 사업장 정보 응답 (공공데이터포털에서 수신된 XML 또는 오류 메시지)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
                  result:
                    type: string
                additionalProperties: true
